# Generated by Django 3.2 on 2023-01-06 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_scholarship_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(default=0, max_length=1000)),
                ('amount', models.CharField(default=12, max_length=1000)),
                ('paid', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField(default=datetime.datetime.today)),
            ],
            options={
                'ordering': ('-date_paid',),
            },
        ),
        migrations.CreateModel(
            name='Referred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personwhorefferred', models.CharField(default=0, max_length=1000)),
                ('personrefferred', models.CharField(max_length=1000)),
                ('date_refferred', models.DateTimeField(default=datetime.datetime.today)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date_refferred',),
            },
        ),
    ]
