# Generated by Django 3.2 on 2023-01-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_adslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralbonu',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
