# Generated by Django 3.2 on 2023-01-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_referralbonu_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralbonu',
            name='amount',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
