# Generated by Django 3.2 on 2023-01-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230107_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='expire',
            new_name='status',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='address',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
