# Generated by Django 3.2 on 2023-01-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_websitelinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAdsContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
