# Generated by Django 3.2 on 2023-01-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_webadscontainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelinks',
            name='name',
            field=models.CharField(max_length=1000000),
        ),
    ]
