# Generated by Django 3.2 on 2023-01-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_websitelinks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslink',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='webadscontainer',
            name='name',
            field=models.TextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='websitelinks',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
