# Generated by Django 3.2 on 2023-01-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230115_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Websitelinks',
            new_name='Websitelink',
        ),
    ]
