# Generated by Django 4.0 on 2023-01-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_body_footer_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Body',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
