# Generated by Django 4.0 on 2023-01-19 10:34

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0017_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', models.CharField(default=0, max_length=1000, unique=True)),
                ('front', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('back', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
